CRYPTO_SYMBOLS = {
        "BTC": "Bitcoin",
        "ETH": "Ethereum",
        "XRP": "XRP",
        "USDT": "Tether USDt",
        "BNB": "BNB",
        "SOL": "Solana",
        "USDC": "USDC",
        "TRX": "TRON",
        "DOGE": "Dogecoin",
        "ADA": "Cardano",
        "LINK": "Chainlink",
        "HYPE": "Hyperliquid",
        "XLM": "Stellar",
        "SUI": "Sui",
        "USDe": "Ethena USDe",
        "BCH": "Bitcoin Cash",
        "HBAR": "Hedera",
        "AVAX": "Avalanche",
        "LEO": "UNUS SED LEO",
        "LTC": "Litecoin",
        "TON": "Toncoin",
        "SHIB": "Shiba Inu",
        "UNI": "Uniswap",
        "DOT": "Polkadot",
        "DAI": "Dai",
        "BGB": "Bitget Token",
        "XMR": "Monero",
        "CRO": "Cronos",
        "AAVE": "Aave",
        "OKB": "OKB",
        "PEPE": "Pepe",
        "MNT": "Mantle",
        "ENA": "Ethena",
        "TAO": "Bittensor",
        "ETC": "Ethereum Classic",
        "NEAR": "NEAR Protocol",
        "APT": "Aptos",
        "ONDO": "Ondo",
        "PI": "Pi",
        "ICP": "Internet Computer",
        "ARB": "Arbitrum",
        "POL": "POL (prev. MATIC)",
        "USD1": "World Liberty Financial USD",
        "KAS": "Kaspa",
        "GT": "GateToken",
        "ALGO": "Algorand",
        "ATOM": "Cosmos",
        "VET": "VeChain",
        "PENGU": "Pudgy Penguins",
        "RENDER": "Render",
        "WLD": "Worldcoin",
        "SEI": "Sei",
        "IP": "Story",
        "BONK": "Bonk",
        "TRUMP": "OFFICIAL TRUMP",
        "FLR": "Flare",
        "FIL": "Filecoin",
        "FET": "Artificial Superintelligence Alliance",
        "KCS": "KuCoin Token",
        "JUP": "Jupiter",
        "XDC": "XDC Network",
        "FDUSD": "First Digital USD",
        "SKY": "Sky",
        "FORM": "Four",
        "INJ": "Injective",
        "QNT": "Quant",
        "TIA": "Celestia",
        "OP": "Optimism",
        "PYUSD": "PayPal USD",
        "CRV": "Curve DAO Token",
        "STX": "Stacks",
        "SPX": "SPX6900",
        "AERO": "Aerodrome Finance",
        "LDO": "Lido DAO",
        "IMX": "Immutable",
        "PUMP": "Pump.fun",
        "FLOKI": "FLOKI",
        "PAXG": "PAX Gold",
        "GRT": "The Graph",
        "S": "Sonic",
        "CFX": "Conflux",
        "PENDLE": "Pendle",
        "CAKE": "PancakeSwap",
        "ENS": "Ethereum Name Service",
        "KAIA": "Kaia",
        "FARTCOIN": "Fartcoin",
        "RAY": "Raydium",
        "XTZ": "Tezos",
        "WIF": "dogwifhat",
        "NEXO": "Nexo",
        "XAUt": "Tether Gold",
        "VIRTUAL": "Virtuals Protocol",
        "A": "Vaulta",
        "THETA": "Theta Network",
        "IOTA": "IOTA",
        "MORPHO": "Morpho",
        "JASMY": "JasmyCoin",
        "GALA": "Gala",
        "SAND": "The Sandbox",
        "AB": "AB",
        "PYTH": "Pyth Network",
        "RLUSD": "Ripple USD",
        "ZEC": "Zcash",
        "BTT": "BitTorrent [New]",
        "JTO": "Jito",
        "FLOW": "Flow",
        "DEXE": "DeXe",
        "WAL": "Walrus",
        "MANA": "Decentraland",
        "B": "BUILDon",
        "BSV": "Bitcoin SV",
        "DEEP": "DeepBook Protocol",
        "ETHFI": "ether.fi",
        "TUSD": "TrueUSD",
        "STRK": "Starknet",
        "DYDX": "dYdX",
        "HNT": "Helium",
        "SYRUP": "Maple Finance",
        "BRETT": "Brett (Based)",
        "CORE": "Core",
        "NEO": "Neo",
        "USDD": "USDD",
        "RSR": "Reserve Rights",
        "M": "MemeCore",
        "NFT": "APENFT",
        "SUN": "Sun [New]",
        "ZK": "ZKsync",
        "RUNE": "THORChain",
        "APE": "ApeCoin",
        "AR": "Arweave",
        "XCN": "Onyxcoin",
        "AIOZ": "AIOZ Network",
        "COMP": "Compound",
        "EGLD": "MultiversX",
        "EIGEN": "EigenLayer",
        "ZBCN": "Zebec Network",
        "KAVA": "Kava",
        "MOG": "Mog Coin",
        "XEC": "eCash",
        "SUPER": "SuperVerse",
        "CVX": "Convex Finance",
        "CHZ": "Chiliz",
        "AXS": "Axie Infinity",
        "ATH": "Aethir",
        "W": "Wormhole",
        "WEMIX": "WEMIX",
        "RON": "Ronin",
        "BEAM": "Beam",
        "ZRO": "LayerZero",
        "1INCH": "1inch Network",
        "GNO": "Gnosis",
        "MOVE": "Movement",
        "JST": "JUST",
        "SNEK": "Snek",
        "CTC": "Creditcoin",
        "LUNC": "Terra Classic",
        "TWT": "Trust Wallet Token",
        "AXL": "Axelar",
        "AMP": "Amp",
        "FTT": "FTX Token",
        "AKT": "Akash Network",
        "TOSHI": "Toshi",
        "DCR": "Decred",
        "ZORA": "ZORA",
        "TURBO": "Turbo",
        "DASH": "Dash",
        "LPT": "Livepeer",
        "BERA": "Berachain",
        "POPCAT": "Popcat (SOL)",
        "IOTX": "IoTeX",
        "BIO": "Bio Protocol",
        "DOG": "Dog (Bitcoin)",
        "KAITO": "KAITO",
        "SAFE": "Safe",
        "VELO": "Velo",
        "MEW": "cat in a dogs world",
        "MOCA": "Moca Network",
        "YZY": "YZY MONEY",
        "QTUM": "Qtum",
        "OM": "MANTRA",
        "KSM": "Kusama",
        "TFUEL": "Theta Fuel",
        "FRAX": "Frax (prev. FXS)",
        "GLM": "Golem",
        "MX": "MX Token",
        "CHEEMS": "Cheems (cheems.pet)",
        "EURC": "EURC",
        "SFP": "SafePal",
        "CKB": "Nervos Network",
        "MINA": "Mina",
        "SNX": "Synthetix",
        "GAS": "Gas",
        "BAT": "Basic Attention Token",
        "PLUME": "Plume",
        "USELESS": "Useless Coin",
        "ZIL": "Zilliqa",
        "PNUT": "Peanut the Squirrel",
        "PROVE": "Succinct",
        "SKL": "SKALE",
        "SUSHI": "SushiSwap"
}