# Generated by Django 5.2.14 on 2026-05-15 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_remove_client_trainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('area', models.PositiveIntegerField(verbose_name='Площадь (кв.м)')),
                ('capacity', models.PositiveIntegerField(verbose_name='Вместимость (человек)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hall_images/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Зал',
                'verbose_name_plural': 'Залы',
            },
        ),
        migrations.RemoveField(
            model_name='training',
            name='trainer',
        ),
        migrations.AddField(
            model_name='training',
            name='trainers',
            field=models.ManyToManyField(related_name='trainings', to='gym.trainer', verbose_name='Тренеры'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='gym.hall', verbose_name='Зал'),
        ),
        migrations.AddField(
            model_name='training',
            name='hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gym.hall', verbose_name='Зал'),
        ),
    ]
