# Generated by Django 5.2.14 on 2026-05-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_hall_remove_training_trainer_training_trainers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingtype',
            name='type',
            field=models.CharField(choices=[('cardio', 'Кардио'), ('strength', 'Силовая'), ('yoga', 'Йога'), ('group', 'Групповая'), ('functional', 'Функциональная')], default='group', max_length=20, verbose_name='Тип'),
        ),
    ]
