def get_help_text() -> str:
    return (
        "<b>📚 Bot Commands</b>\n\n"
        "<b>ℹ️ Help</b>\n"
        " • /help\n"
        " ➝ Show help message with all commands\n\n"
        "<b>🔑 Start & Menu</b>\n"
        " • /start\n"
        " ➝ Open main menu with quick portfolio overview via buttons\n\n"
        "<b>💹 Check Prices</b>\n"
        " • /check <code>asset_type</code> [<code>app_id</code>] <code>asset_name</code>\n"
        " ➝ Get current price for any asset\n"
        " ▸ <b>asset_type</b>: <code>stock</code>, <code>crypto</code>, or <code>steam</code>\n"
        " ▸ <b>app_id</b>: Required for Steam items (e.g., <code>730</code> for CS2)\n\n"
        " Examples:\n"
        "   <code>/check stock AMD</code>\n"
        "   <code>/check crypto ETH</code>\n"
        "   <code>/check steam 730 Danger Zone Case</code>\n\n"
        "<b>📊 Portfolio Management</b>\n"
        " Use the optional <code>-p &lt;price&gt;</code> parameter in /add to set your custom purchase price "
        "(e.g., <code>-p 170</code> or <code>-p 170.50</code>).\n\n"
        " • /add <code>asset_type</code> [<code>app_id</code>] <code>asset_name</code> <code>quantity</code> [-p <code>price</code>]\n"
        " ➝ Add asset to your portfolio\n"
        " Examples:\n"
        "   <code>/add stock AMD 2</code>\n"
        "   <code>/add stock AMD 20 -p 170.50</code>\n"
        "   <code>/add crypto ETH 0.5</code>\n"
        "   <code>/add steam 730 Danger Zone Case 10 -p 2.99</code>\n\n"
        " • /remove <code>asset_type</code> [<code>app_id</code>] <code>asset_name</code> [<code>quantity</code>]\n"
        " ➝ Remove asset (or specified quantity) from portfolio\n"
        " Examples:\n"
        "   <code>/remove stock AMD</code> (removes all)\n"
        "   <code>/remove stock AMD 5</code>\n"
        "   <code>/remove steam 730 Danger Zone Case 3</code>\n\n"
        " • /portfolio [<code>all|stock|crypto|steam</code>]\n"
        " ➝ View your portfolio\n"
        " Example: <code>/portfolio stock</code>\n\n"
        "<b>🔔 Price Alerts</b>\n"
        " • /set_alert <code>asset_type</code> [<code>app_id</code>] <code>asset_name</code> <code>condition</code> <code>price</code>\n"
        " ➝ Set a price alert\n"
        " ▸ <b>asset_type</b>: <code>stock</code>, <code>crypto</code>, or <code>steam</code>\n"
        " ▸ <b>app_id</b>: Required for Steam items (e.g., <code>730</code> for CS:GO)\n"
        " ▸ <b>condition</b>: <code>&gt;</code>, <code>&gt;=</code>, <code>&lt;</code>, or <code>&lt;=</code>\n"
        " Examples:\n"
        "   <code>/set_alert stock AMD > 200</code>\n"
        "   <code>/set_alert steam 730 Glove Case > 5</code>\n\n"
        " • /alerts\n"
        " ➝ Show all active alerts\n\n"
        " • /delete_alert <code>id</code>\n"
        " ➝ Remove an alert by ID\n"
        " Example: <code>/delete_alert 1</code>\n\n"
        "<b>📜 History</b>\n"
        " • /history [<code>all|stock|crypto|steam</code>]\n"
        " ➝ View your purchase history\n"
        " Example: <code>/history stock</code>\n\n"
        "◇───────────────────────────────────────────◇\n\n"
        "<b>💡 Tip:</b> Use exact asset names, valid quantities/prices."
    )
